Add a 404 page to display when a file has been deleted
opacity/static-public-share pull request #25
Opened 2022-05-11 16:53 UTC by franky-fk

2022-05-11 18:14 UTC, faizan-firekamp requested changes
Please make the change and test

2022-05-11 18:14 UTC, faizan-firekamp commented on front/src/pages/SharePage/SharePage.tsx
> +  })
lets not even use state, we can just check `file.fileSizeBytes` directly

2022-05-11 18:15 UTC, franky-fk commented on front/src/pages/SharePage/SharePage.tsx
> +  })
@faizan-firekamp I tried that and it was throwing an error. Something about re-rendering several times.

2022-05-11 19:54 UTC, faizan-firekamp approved these changes
Looks good

2022-05-11 19:54 UTC, merged

2022-05-12 17:51 UTC, kamranpirwani commented on front/src/pages/SharePage/SharePage.tsx
> +  if (Number(file.fileSizeBytes) === 0) {
For the file handle I see that's deleted, this should also be catching on the fetch in L35 in order to redirect to 404